### ISSUE TITLE
Cannot load file/ Chronogram Plot Failure

### ISSUE THREAD

**Issue by scubabo** [earnestt1234/FED3_Viz#3]
Hi. I cannot load a .csv or .xlx file despite the fact that all the other files in this group are loading. The error message reads

ValueError: NaTType does not support strftime

Additionally, the option to create line chronograms in not populating. I have worked with this dataset successfully before. But, after re-extracting fed3 viz .exe for the sixth time (separate issue) the line chronogram will not work. 

Help with this issue is much appreciated.

**Comment by earnestt1234** [comment]
@scubabo sorry to hear you are having trouble!  Previously, that error has meant that one file has a bum timestamp (likely the first or last entry in the `MM:DD:YYYY hh:mm:ss` column).  This can happen when there was a writing error from FED, sometimes due to jam or some other issue.  I would check over that file and see if you can find a problematic entry that can be removed.

Aside from that, I might need to see the data in question in order to determine what the problem is.  You can [send me the data](mailto:earnestt1234@gmail.com) if you would like me to take a look (I don't think they can be attached here?).

The chronogram issue I am not sure specifically.  Is it that the option to run the chronogram won't highlight (i.e. the Create Plot button remains inactive), or that you can create the plot but nothing appears?  The first issue happens when the file aren't in a Group.  But if there are issues with one or more files, maybe that is causing an additional problem.  So if we sort out your files, maybe we can revisit this.

I'd be curious to hear your installation issues as well, if there is something you think could be improved!
