### ISSUE TITLE
FED_Viz data loading but only some plots working

### ISSUE THREAD

**Issue by allilink** [earnestt1234/FED3_Viz#8]
Hi Tom! Thank you for this amazing work. I am currently trying to load in some of my FED data to plot. I found that both your example data from the github and my own data only allow me to plot some of the option (i.e. single poke plot is fine, but average poke plot is not). 

Any ideas why this might be?

**Comment by earnestt1234** [comment]
@allilink Hi, sorry for the delay!

For the average poke plots, are you successfully able to place the FEDs into a group?  I.e. highlight the FEDs > Create Group > Enter a group name > OK.  Then the grouped plots should be available.

Beyond that I am not sure offhand.  You can also send me the data so I can verify I can/can't load it on my end

**Comment by allilink** [comment]
Hi! 

I was able to play with it a bit, get the groups to work and all the plots except the progressive ratio ones! I realized we have our files labeled as "closed economy", is that a completely different file and thus won't work with the "progressive ratio" visualization?

If so, I think I should just be able to edit the breakpoint plot code right? Or am I missing something? Thanks so much for your help!!

**Comment by earnestt1234** [comment]
Glad you got the other plots working!

For breakpoints, yes I think that is hard-coded so that it will only be available if the "mode" of each FED is "PR" (progressive ratio).  So short-term  workarounds for this would be:
- Trick the program into thinking your files are PR.  [The logic that assigns the mode is here](https://github.com/earnestt1234/FED3_Viz/blob/master/FED3_Viz/load/load.py#L158-L175).  The specifics will probably depend on the version of FED code you are using, but I think the easiest solution would be go to the Session_Type/Mode columns, and put "PR" in the first row.  You could add these columns if they are not there already.
- Use the breakpoint code outside of FED3_Viz.  The PR Plot functions ([defined here](https://github.com/earnestt1234/FED3_Viz/blob/a12bd2ccb6cae868255efa44c551e1cb95954624/FED3_Viz/plots/plots.py#L2131-L2330)) won't care about the mode.  You could copy these and work with them in a Python script.  You will also at least need  the code for [loading the FED3 files into Python](https://github.com/earnestt1234/FED3_Viz/blob/a12bd2ccb6cae868255efa44c551e1cb95954624/FED3_Viz/load/load.py#L14), and possibly some other helper functions referenced in the source code.
    - Alternatively, I could generate a script from a working PR plot in FED3Viz (using the Plot Code function), and share that with you.
